# Generated by Django 4.1.7 on 2023-04-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="state",
            field=models.TextField(
                choices=[
                    ("Done", "Done"),
                    ("In Progress", "In Progress"),
                    ("To Do", "Todo"),
                    ("Incomplete", "Incopmplete"),
                ],
                default="To Do",
            ),
        ),
    ]
