# Generated by Django 4.1.7 on 2023-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_todoitem_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="state",
            field=models.TextField(
                choices=[
                    ("DONE", "Done"),
                    ("TODO", "To do"),
                    ("IN_PROGRESS", "In progress"),
                    ("INCOMPLETE", "Incomplete"),
                ],
                default="TODO",
            ),
        ),
    ]
